name: Full CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Run tests
      - name: Run tests
        run: npm test

  docker_build_and_deploy:
    needs: test # Ensures this job runs after the tests job

    runs-on: ubuntu-latest

    steps:
      # Checkout the repository again for the Docker job
      - name: Checkout repository
        uses: actions/checkout@v2

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build and tag Docker image
      - name: Build and tag Docker image
        run: |
          docker build -t hotelroom_image .
          docker tag hotelroom_image sidi4pf/hotelroomsidi:latest

      # Push Docker image to Docker Hub
      - name: Push Docker image to Docker Hub
        run: |
          docker push sidi4pf/hotelroomsidi:latest
